title: Uri Cohen
logo: /assets/img/logo.jpg
description: Blavatnik visiting fellow at the Computational and Biological Learning Lab, University of Cambridge
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
